server:
  port: 8761

spring:
  application:
    name: eurekapractice

eureka:
  client:
    register-with-eureka: false # 기본 true, 자신의 정보를 자신에 등록하게 된다. 따라서 등록하지 않기 위하여 false
    fetch-registry: false