spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/test_contents?useUnicode=true&characterEncoding=utf8
    username: root
    password:

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
